"""Replace content with file_url

Revision ID: 90499f1de9e4
Revises: 380d6c004a86
Create Date: 2026-03-17 17:15:47.917557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90499f1de9e4'
down_revision: Union[str, Sequence[str], None] = '380d6c004a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=1024), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
